# Edit this Gemfile to bundle your application's dependencies.
# This preamble is the current preamble for Rails 3 apps; edit as needed.
source 'http://rubygems.org'

gem 'rails', '3.0.6'

gem 'calendar_date_select', '1.16.1'
gem 'authlogic', '2.1.3'
#gem 'actionpack', '2.3.9'
gem 'formtastic', '1.1.0'
gem 'will_paginate', '2.3.12'
gem 'faker', '0.3.1'
gem 'ruby-progressbar', '0.0.10'
gem 'factory_girl', '1.3.3'
gem 'whenever', '0.4.2'
gem 'ruby-prof', '~> 0.15.1'
gem 'simplecov', '~> 0.9.0'
gem 'searchlogic', '2.4.19'
gem 'chronic', '0.2.3'
gem 'daemons', '1.0.10'
gem 'cucumber', '0.6.4'
gem 'email_spec', '0.6.2'
gem 'timecop', '0.3.4'
gem 'nokogiri', '1.4.1'
gem 'ruby-terminfo', '0.1.1'
gem 'cucumber-rails', '0.3.0'
gem 'database_cleaner', '0.5.0'
gem 'webrat', '0.7.3'
gem 'rspec', '1.3.2'
gem 'rspec-rails', '1.3.2'
gem 'spreadsheet'
gem 'fastercsv'
gem 'validates_as_email_address'
gem 'less'
gem 'mimetype-fu', :require => 'mimetype_fu'
gem 'delayed_job', '1.8.5'
gem 'prawn', '0.7.2'
gem 'prawn-layout', '0.7.2', :require => 'prawn/layout'
