module AvailabilityHelper
  # Because we alter the URL generated by routing, we need to pass in
  # in the url form_for should use otherwise it errors out
  def availability_form_url(staff=@staff, availability=@availability)
    availability.nil? || availability.new_record? ?
      staff_availabilities_path(staff) :
      staff_availability_path(staff, availability)
  end

  def split_availability_form_url(staff=@staff, availability=@availability)
    split_staff_availability_path(staff, availability)
  end

  # Can't use the Rails built in helper because it only does 0 to 23,
  # and only does one digit (not two)
  def hour_selector(name, current=nil, options={})
    values = [['', '']] + (00..24).collect { |i| [i.to_two_digit, i.to_two_digit] }
    select_tag(name, options_for_select(values, (!current.blank? ? (current.to_two_digit) : nil)), options)
  end

  def add_start_finish_comment_link_for(day)
    link_to_function('Add Another', nil) do |page|
      page.insert_html :bottom, "#{day}_start_finish_comment_editors",
                       :partial => 'start_finish_comment',
                       :locals => { :day => day, :with_close => true }
    end
  end

  # In Javascript, when you do 'new Date(yyyy, mm, dd)', Javascript expects
  # a month value one less than the actual month (i.e. months start at 0, not 1)
  def convert_date_to_js(date)
    date.year.to_s + ',' + (date.month).to_s + ',' + date.day.to_s
  end
end
